### ISSUE TITLE
After the successful installation, the virtual cam cannot be found by ffmpeg

### ISSUE THREAD

**Issue by qing-wang** [daily-co/daily-virtual-camera#4]
After the successful installation, the virtual cam cannot be found by ffmpeg. 

<img width="971" alt="截圖 2023-08-19 下午11 00 11" src="https://github.com/daily-co/daily-virtual-camera/assets/1468273/dc8f13b2-7651-4a1f-afe5-9abcff871abe">

**Comment by DRESSXcom** [comment]
The same for me. I have found that the gstreamer framework removes the extension from the list. Any ideas on how to restore it?

**Comment by DRESSXcom** [comment]
@aconchillo Can you help us with the issue please?

**Comment by aconchillo** [comment]
This should now be fixed after #3 . You will need to:

- Install GStreamer >= 1.22.0 https://gstreamer.freedesktop.org/pkg/osx/
- Uninstall the previously installed virtual camera system extension (using the virtual camera app).
- Reboot the computer.
- Build the virtual camera app with latest changes from the repo.
- Install the virtual camera app in /Applications.
- Install the virtual camera system extension (using the new virtual camera app)

Let us know if you find any issues.

**Comment by quqixun** [comment]
@aconchillo 
Thanks for updating.
However, after building, there was no Daily Virtual Camera.app in Products dir without error showing.

I installed GStreamer == 1.22.0.
I changed the team and the bundle identifier of both daily-virtual-camera and cam.
I had no idea what is wrong.

Could you please provide the installation guide with more details?

**Comment by aconchillo** [comment]
The updates on this PR also assume that you have installed GStreamer in `/Library/Frameworks/GStreamer.framework` which I believe is the default. The reason for this assumption is because the extension doesn't embed the GStreamer.framework (because of the size), so it just needs that the framework is installed in a specific location in the system in order to found it.

**Comment by quqixun** [comment]
@DRESSXcom @aconchillo 
Thanks fir your help, I have managed to build the app successfully.
The problem is that the default Product Scheme is the cam extension, but is should be the Daily Virtual Camera app.

**Comment by aconchillo** [comment]
> @DRESSXcom @aconchillo Thanks for your help, I have managed to build the app successfully. The problem is that the default Product Scheme is the cam extension, but is should be the Daily Virtual Camera app.

Thank you. I updated the README to make it clear the right scheme needs to be selected.
